apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask-svc
  name: flask-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: flask-app
  type: NodePort
